#
# Rules to add CMSIS
#

# CMSIS
CMSIS_DIR := $(COMMONLIB_DIR)/CMSIS/CMSIS_STM32F4
CMSIS_DEVICE_DIR := $(CMSIS_DIR)/Device/ST/STM32F4xx
STARTUP_DIR := $(CMSIS_DEVICE_DIR)/Source

SRC += $(CMSIS_DEVICE_DIR)/Source/system_stm32f4xx.c

EXTRAINCDIRS += $(CMSIS_DIR)/Include
EXTRAINCDIRS += $(CMSIS_DEVICE_DIR)/Include
