#
# Rules to add CMSIS
#

# CMSIS
CMSIS_DIR := $(COMMONLIB_DIR)/CMSIS/CMSIS_STM32F1
CMSIS_DEVICE_DIR := $(CMSIS_DIR)/Device/ST/STM32F10x
STARTUP_DIR := $(CMSIS_DEVICE_DIR)/startup/gcc_ride7

SRC += $(CMSIS_DIR)/Core/CM3/core_cm3_rev.c
SRC += $(CMSIS_DEVICE_DIR)/system_stm32f10x.c

EXTRAINCDIRS += $(CMSIS_DIR)/Core/CM3
EXTRAINCDIRS += $(CMSIS_DEVICE_DIR)
